---
  - name: Install required packages
    apt: name={{ item }} state=latest update_cache=yes force_apt_get=yes
    loop: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'gnupg', 'python3-pip', 'python3-setuptools']

  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

  - name: Add Docker repo
    apt_repository:
      repo: deb https://download.docker.com/linux/debian stretch stable
      state: present

  - name: Install Docker
    apt: update_cache=yes name=docker-ce state=latest

  - name: Install python module to Docker
    pip:
      name: docker