---
- name: Include var file
  include_vars: group_vars/vars.yaml

- name: Copy my.cnf
  template:
    src: my.cnf.j2
    dest: /opt/my.cnf

- name: Run database container
  docker_container:
    name: zabbix-db
    image: mariadb:latest
    state: started
    recreate: yes
    env:
      MARIADB_USER: "{{ db_user }}"
      MARIADB_PASSWORD: "{{ db_user_password }}"
      MARIADB_ROOT_PASSWORD: "{{ db_root_password }}"
      MYSQL_DATABASE: "{{ db }}"
    published_ports:
      - '3306:3306'
    volumes:
      - "/opt/zabbix:/var/lib/mysql"
      - "/opt/my.cnf:/etc/mysql/my.cnf"

- name: Copy init_replica.sh
  template:
    src: init_replica.sh.j2
    dest: /opt/init_replica.sh
    mode: 0755
  
- name: Init replication
  shell: /opt/init_replica.sh
  when: role == "master"