---
- name: Start zabbix-frontend
  docker_container:
    name: zabbix-frontend
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-latest
    state: started
    recreate: yes
    published_ports:
      - '8080:8080'
      - '8443:8443'
    links:
      - 'zabbix-backend:zabbix-server'
      - 'zabbix-db:mysql'
    env:
      DB_SERVER_HOST: zabbix-db
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      ZBX_SERVER_HOST: zabbix-server
      MYSQL_DATABASE: zabbixdb
      PHP_TZ: Europe/Moscow