---
- name: Include var file
  include_vars: group_vars/vars.yaml

- name: Start zabbix-backend
  docker_container:
    name: zabbix-backend
    image: zabbix/zabbix-server-mysql:ubuntu-5.4-latest
    state: started
    recreate: yes
    published_ports:
      - '10051:10051'
    env:
      DB_SERVER_HOST: "{{ db_master_host }}"
      MYSQL_USER: "{{ db_user }}"
      MYSQL_PASSWORD: "{{ db_user_password }}"
      MYSQL_DATABASE: "{{ db }}"