---
- name: Run postgres container
  docker_container:
    name: postgres
    image: postgres
    state: started
    recreate: yes
    env:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    published_ports:
      - '5432:5432'
    # supported in ansible 2.9
    #healthcheck:
    #  test: ["CMD-SHELL", "pg_isready -U postgres"]
    #  interval: 5s
    #  timeout: 5s
    #  retries: 5